# Generated by Django 5.0.6 on 2024-06-02 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='media/company_logo')),
                ('company_location', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_salary', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
