# Generated by Django 5.0.6 on 2024-06-05 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('resume', models.FileField(upload_to='media/resume')),
                ('photo', models.ImageField(upload_to='media/applicant_photo')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobmodel')),
            ],
        ),
    ]
