# Generated by Django 4.2.6 on 2024-06-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
    ]
