# Generated by Django 5.0.6 on 2024-06-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_applyjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='deadline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
