# Generated by Django 4.2.6 on 2024-06-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0007_remove_consumedcalories_total_calorie_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Admin', 'Admin'), ('Restaurant', 'Restaurant')], max_length=20, null=True),
        ),
    ]
