# Generated by Django 5.0.3 on 2024-06-28 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0010_userfollow_userpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollow',
            name='is_following',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
