# Generated by Django 5.0.3 on 2024-06-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0011_userfollow_is_following_alter_userfollow_follow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollow',
            name='is_following',
        ),
    ]
