# Generated by Django 5.0.6 on 2024-06-30 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0014_userpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='image',
        ),
        migrations.CreateModel(
            name='postImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_pics/')),
                ('date', models.DateField(auto_now_add=True)),
                ('userpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit_app.userpost')),
            ],
        ),
    ]
