# Generated by Django 4.2.6 on 2024-07-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0015_remove_userpost_image_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
