# Generated by Django 5.0.6 on 2024-07-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0017_addrestaurantfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrestaurantfood',
            name='category',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('grain', 'Grain'), ('protein', 'Protein'), ('dairy', 'Dairy'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('fast_food', 'Fast Food')], max_length=100),
        ),
    ]
